### ISSUE TITLE
Make `MockProver` do multi-phase synthesis like real prover

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/halo2#102]
In order to make debugging easier, it's better for `MockerProver` to also do multi-phase synthesis just like real prover, to avoid some cases that succeed with `MockProver` but fail with real prover.

Tho it will increase the synthesis time for those circuits that use multiple phases, but it should still be better than debugging multi-phase circuit with real prover.

**Comment by CPerezz** [comment]
Putting this aside as we will be working on the HI-LO approach for the next weeks/months
