### ISSUE TITLE
Host docs on github pages

### ISSUE THREAD

**Issue by jonathanpwang** [privacy-scaling-explorations/halo2#140]
It's useful to have an easy place to access the rust generated docs online. The zcash/halo2 has docs on docs.rs but this fork doesn't. You can generate docs and host them on this repo's github pages by following this: https://dev.to/deciduously/prepare-your-rust-api-docs-for-github-pages-2n5i (see the script at the bottom). 

I set up an example here: https://axiom-crypto.github.io/halo2/halo2_proofs/ 
But I think it's probably better for this fork to have its own docs page.

**Comment by CPerezz** [comment]
Thanks for the suggestion @jonathanpwang !! Let's see if someone wants to take this as seems fairly easy (we will enable gh-pages and so on). Otherwise, we'll do it within next weeks! :)

**Comment by thogiti** [comment]
Hello @CPerezz. I am a ZK Fellow from PSE's summer ZK Fellow program. 

I completed this task and now we can see the PSE's docs on github pages host. You can test it here:

https://thogiti.github.io/halo2/halo2/

I added a workflow through Github action to automate building the docs from PSE's root repo, add necessary index.html file in the correct path and deploy to github pages. 

https://github.com/thogiti/halo2/blob/main/.github/workflows/docs-ghpages.yml

I also opened a PR on PSE's halo2 repo. If it is approved then I can update the link to the documentation from the main repo as a separate contribution.

**Comment by thogiti** [comment]
We should close this issue since it was addressed and merged in [PR 204](https://github.com/privacy-scaling-explorations/halo2/pull/204).

**Comment by han0110** [comment]
Thanks for reminding! Closing this now.
