### ISSUE TITLE
Allow names to have non-static names

### ISSUE THREAD

**Issue by Brechtpd** [privacy-scaling-explorations/halo2#142]
Currently when creating gates/lookups/constraints halo2 only accepts strings of type `&'static str`. This is fine in most cases, however in some cases these names need to be generated at runtime to be able to generate useful names for a particular constraints (think any automatic system that needs to generate these). Currently the only usable workaround is to do something like `Box::leak(name.into_boxed_str())` which obviously is not ideal.

The goal is to modify halo2 so it can accept both a static string (also important for backward compatibility) and a runtime string type.

As there strings are only stored once per lookup/gate/constraint this should not have any significant impact on anything important. `assign_advice` also already supports passing in a `String`.

**Comment by han0110** [comment]
Resolved by https://github.com/privacy-scaling-explorations/halo2/pull/156
