### ISSUE TITLE
Create new tag to use https://github.com/privacy-scaling-explorations/halo2/pull/149 in zkevm-circuits

### ISSUE THREAD

**Issue by leolara** [privacy-scaling-explorations/halo2#160]
Please

**Comment by ChihChengLiang** [comment]
https://github.com/privacy-scaling-explorations/halo2/pull/149 Was merged on Feb 23, but the latest release tag is https://github.com/privacy-scaling-explorations/halo2/releases/tag/v2023_02_02 on Feb 2. We still need a new tag.
