### ISSUE TITLE
Adding a constructor for `ParamsKZG`

### ISSUE THREAD

**Issue by Ethan-000** [privacy-scaling-explorations/halo2#163]
Hey

I'm wondering if a [ParamsKZG](https://github.com/privacy-scaling-explorations/halo2/blob/fcdd5b910d92ab278d679cf8aa176c885455aa6c/halo2_proofs/src/poly/kzg/commitment.rs#L22) constructor can be added so that it can be initialized through `k`, `n`, `g`, `g_lagrange`, `g2`,  `s_g2` 🙂. Currently these fields are only accessible through the crate and there's no function that can do this

```
    pub(crate) k: u32,
    pub(crate) n: u64,
    pub(crate) g: Vec<E::G1Affine>,
    pub(crate) g_lagrange: Vec<E::G1Affine>,
    pub(crate) g2: E::G2Affine,
    pub(crate) s_g2: E::G2Affine,
```

**Comment by CPerezz** [comment]
> Yeah I was trying to initialize the parameters from an existing setup ceremony

Ohh I see.
Basically you have the powers of Tau but not in the format we need them for you to serialize the object. Is that the case?


If so, if you want to make a PR, we definitely appreciate it! Otherwise, we'll try to implement this as soon as we have time for it! :smile:

**Comment by kilic** [comment]
> Why any of these two things doesn't work for you? What are you trying to do?

Other option is that to make a file that halo2 can deserialize so that we can ensure that parameters can pass assertions while reading

**Comment by han0110** [comment]
> Yeah I was trying to initialize the parameters from an existing setup ceremony

btw for reading from existing ceremony, we also have some format converted already in this repo https://github.com/han0110/halo2-kzg-srs (currently we have converted https://github.com/weijiekoh/perpetualpowersoftau and https://github.com/iden3/snarkjs).
