### ISSUE TITLE
bn256 support for sha256 gadget

### ISSUE THREAD

**Issue by StefanosChaliasos** [privacy-scaling-explorations/halo2#182]
Hey, is it possible for the sha256 gadget to support both the Pallas and bn256 curves? The main reason is that you cannot use KZG with the Sha256 gadget rn. Do I miss something here? One dirty solution is replacing Pallas (or having pallas_sha256 and bn256_sha256) with bn256, as done here: https://github.com/celer-network/halo2/pull/4/files. Is there a drawback to this solution?

**Comment by StefanosChaliasos** [comment]
Yeah, sorry for the misunderstanding. They just replaced Pallas with Bn256. Should we close the issue, and maybe re-open it if anyone wants to work on it (I don't have time atm, but I will be happy to implement it once I have some free time)?

**Comment by CPerezz** [comment]
Sure! That makes complete sense @StefanosChaliasos  :)
