### ISSUE TITLE
Solidity Verifier

### ISSUE THREAD

**Issue by alexander-camuto** [privacy-scaling-explorations/halo2#191]
Hey all 

As part of improving useability of H2 tooling, we have a solidity verifier / wrapper for the yul / assembly code that get generated in this repo. 

You can find the functions we've created for doing so here: 
https://github.com/zkonduit/ezkl/blob/b214d64cb7f336c23426c80512f9de9e494ea451/src/eth.rs#L579

And the associated `.sol` template that gets populated with the assembly here: 
https://github.com/zkonduit/ezkl/blob/b214d64cb7f336c23426c80512f9de9e494ea451/contracts/VerifierBase.sol

My sense is that this could be broadly useful to others and was wondering whether it would be worth: 
- upstreaming this to one of the PSE Halo2 related repos 
- and if so where would be the best place to house this -- possibly snark-verifier ?

**Comment by han0110** [comment]
That idea sounds great! I think we can have another crate like `halo2_solidity_verifier` to hold the whole new code generator considering the logic highly depends on `halo2_proofs` itself, or having another standalone repo for also sounds nice imo.

**Comment by alexander-camuto** [comment]
Sweet -- what's the best way to create a standalone repo within the pse org ?

**Comment by CPerezz** [comment]
> Sweet -- what's the best way to create a standalone repo within the pse org ? 

I love the idea!! I can take care if you want. That would be a really nice improvement to Halo2 which also doesn't make the Halo2 codebase more complex!!!

Nice!!!

**Comment by alexander-camuto** [comment]
yes please :) can you add me as a contributor to the new repo so I can easily open PRs etc...

**Comment by CPerezz** [comment]
Hey @alexander-camuto feel free to push here: https://github.com/privacy-scaling-explorations/halo2_solidity_verifier

You should have an invite.
Then we can move on from there coordinating with @han0110

**Comment by alexander-camuto** [comment]
amazing thank you

**Comment by CPerezz** [comment]
Done in https://github.com/privacy-scaling-explorations/halo2_solidity_verifier/pull/1
