### ISSUE TITLE
Implement `Sum` & `Prod` trait impls for Expression

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2#205]
There are some times where we do need to sum a bunch of `Expressions` in a `Vec`. When this happens, we're forced to use `fold()` instead of just using `sum()` which would lead to less boilerplate.

Would be nice to have that implemented.

**Comment by chokermaxx** [comment]
wanna work on this!

**Comment by CPerezz** [comment]
@chokermaxx assigned to you!
