### ISSUE TITLE
Improve security of Halo2 with `SharedSecret` to prevent leaking secret

### ISSUE THREAD

**Issue by chiro-hiro** [privacy-scaling-explorations/halo2#214]
Hi guys!,

I found a potential issue in managing secret. Let's take the [KZG setup](https://github.com/privacy-scaling-explorations/halo2/blob/main/halo2_proofs/src/poly/kzg/commitment.rs#L70) for example:

```rust
let s = <E::Scalar>::random(rng);
```

### What's the problem here?

1. `Copy` trait was implemented for `Engine::Scalar` that mean, secret `s` may be copied with any assignment.
2. After we leave the code block, memory occupied by `s` will be returned but it might not be zeroized.

### Proposal

To change this a struct of `SharedSecret` might need to be implemented to keep a single instance that reference to the secret.

```rust
#[derive(Debug)]
/// Shared Secret
pub struct SharedSecret<E: Engine> {
    pub(crate) s: Arc<Mutex<E::Scalar>>,
}
```

Beside the `Engine::Scalar` must have the ability to be zeroized:

```rust
pub fn zeroize(&mut self) {
    for i in 0..*self.0.len() {
        *self.0[i] ^= *self.0[i];
    }
}
```

`Drop` trait might need to implement for `SharedSecret` so we can perform `Engine::Scalar::zeroie()` before we return the memory that occupied by the program.

**Comment by CPerezz** [comment]
Hey! In this specific case, as discussed with @han0110 in private this is not an issue as the `setup` function is only meant to be used in testing.

BUT, it's true that there are some places within the protocol where this might make sense. 
I think we can definitely address this in the future once the codebase is a bit more mature.
