### ISSUE TITLE
Add a new page in book to list all features PSE fork adds

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/halo2#223]
Things we have added:

- `CommitmentScheme`
- `Evaluator`
- `Expression::Challenge`
- `ConstraintSystem::{lookup_any,shuffle}`
- `MockProver::verify_{par,at_rows_par}`
- Serialization for pk/vk
- ...

**Comment by CPerezz** [comment]
We should also add #220 as is going to be merged soon
