### ISSUE TITLE
Add an assertion to prevent dynamic lookups without selectors/fixed

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2#224]
This would prevent errors like PSE-ZKEVM dynamic lookups to happen unnoticed.

**Comment by davidnevadoc** [comment]
Can you provide some explanation/ example of this error @CPerezz ? Thanks!

**Comment by jonathanpwang** [comment]
Here is an example: the diff of the PR shows what changed, and there is a RAM example test. https://github.com/axiom-crypto/halo2-lib/pull/206
