### ISSUE TITLE
Include `shuffle` within transcript when empty prior to a new major version release

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2#227]
>Just realized the change might lead to different `transcript_repr` even the circuit doesn't use `shuffle`, so I think to keep backward compatability we need to skip the `shuffle` field when it's empty.
>
>_Originally posted by @han0110 in https://github.com/privacy-scaling-explorations/halo2/issues/195#issuecomment-1707847681_

**Comment by davidnevadoc** [comment]
Doesn't the comment say the opposite?

**Comment by CPerezz** [comment]
> Doesn't the comment say the opposite? @CPerezz

That's why I say "prior to a new major release". By that I mean that we can just assume we break backwards compatibility with a new major version release. 
Hence we don't care more about this.
