### ISSUE TITLE
issue when multiple shuffles to compress

### ISSUE THREAD

**Issue by mooreland** [privacy-scaling-explorations/halo2#237]
as we know, shuffle just process the one to one map and they can be disorder like [1,2,3] to [3,1,2] and just totally same elements.
if multiple shuffle involved, they will be compressed to one column by random challenge.
in https://github.com/privacy-scaling-explorations/halo2/blob/6fc6d7ca018f3899b030618cb18580249b1e7c82/halo2_proofs/examples/shuffle_api.rs#L197,
we take the ut as example:
shuffle_A:  input0:[1,    2,     4,   1 ],  shuffle0: [4,     1,    1,   2 ]
shuffle_B:  input1:[ 10, 20,  40, 10],  shuffle1:  [40,  10, 10, 20]
it will be ok as the shuffle_B 's input and shuffle keep consistent order as shuffle_A's, like input0's 1 to input1's 10 and shuffle0's 1,to shuffle1's 10
however, in production,  different shuffle may not keep some relationships, if we change the shuffle_B's inputs order, it will failed.
shuffle_B:  input1:[ **20, 10,**  40, 10],  shuffle1:  [40,  10, 10, 20]
as when compressed, input0's 1 will combine with input1's 20 , and shuffle0's 1 still combine 10.

but only take shuffle_B alone, it is success.

to solve this, in my opinion, it may still need involved the permutation, but it is lookup_any does

**Comment by mooreland** [comment]
sorry，I have not fully understand, there should be  some restriction when multiple column involved in same row, which is same in lookup table.  but most of scenario, different lookup will be distributed in different rows.

**Comment by CPerezz** [comment]
I'm still not sure I follow the exact issue though. 

Could you elaborate a bit more?
