### ISSUE TITLE
Split `create_proof` inner logic in focused functions/stages

### ISSUE THREAD

**Issue by mratsim** [privacy-scaling-explorations/halo2#247]
The current `create_proof` is a behemoth function that does too much.

This is affecting:
- understanding and velocity when contributing proof-related code (lookup improvement in our case)
- debugging, auditing and maintenance
- contributing and testing
- memory usage, because data necessary for the initial stages can be dropped. I assume unused Rust's `Vec` are garbage collected only at function exit

The function sits at ~650 lines

https://github.com/privacy-scaling-explorations/halo2/blob/0c3e3b569519b86653a64f412bbce17e4e8acac4/halo2_proofs/src/plonk/prover.rs#L33-L699

cc @AlekseiVambol @Brechtpd @CeciliaZ030

**Comment by ed255** [comment]
Totally agree!  In the frontend-backend PR I already split the create_proof into 3 parts (which are necessary for the split): https://github.com/privacy-scaling-explorations/halo2/blob/d350e727f11daf7c19dfe5ae6bddcc7b073fdf5d/halo2_proofs/src/plonk/prover.rs#L149
I think it can be split further into smaller functions.  I would suggest waiting until https://github.com/privacy-scaling-explorations/halo2/pull/243 is merged to work on this.
