### ISSUE TITLE
Add `LagrangeBasis` trait

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/halo2#279]
Currently `Basis` can refer to coefficients, lagrange basis or extended lagrange basis.
Some functions like

https://github.com/privacy-scaling-explorations/halo2/blob/0b75a92a1c9c59b19304632e0bac6c788190a3aa/halo2_backend/src/plonk/evaluation.rs#L836

does not make sense for coeffients. Needs to work only with lagrange.

the proposal is to add a new trait `LagrangeBasis`

```
pub trait LagrangeBasis: Copy + Debug + Send + Sync {}
impl LagrangeBasis for LagrangeCoeff {}
impl LagrangeBasis for ExtendedLagrangeCoeff {}
```

to use them for Lagrange basis polynomials.

**Comment by ed255** [comment]
This is addressed via https://github.com/privacy-scaling-explorations/halo2/pull/289 right?
