### ISSUE TITLE
Fix the changes introduced in getrandom import as dep

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/halo2#285]
Changes done in [09aaf97](https://github.com/privacy-scaling-explorations/halo2/pull/281/commits/09aaf9781567bde2979f35ddabc2b43148d66173) should be reverted and we should bring back the dependency import only as `dev-dependency`.

**Comment by duguorong009** [comment]
@CPerezz 
I found the origin of issue & created the PR to fix it.
Pls review the PR.

**Comment by duguorong009** [comment]
One additional topic is that the `rust-toolchain` can be downgraded to `v1.67.0` as before.
Do you think it is better to keep the `rust-toolchain` as `v1.73.0`? or downgrade it to `v1.67.0`? @CPerezz

**Comment by duguorong009** [comment]
> > One additional topic is that the `rust-toolchain` can be downgraded to `v1.67.0` as before. Do you think it is better to keep the `rust-toolchain` as `v1.73.0`? or downgrade it to `v1.67.0`? @CPerezz
> 
> I'd roll it back. Unless until a bump is needed.

Okay, then, how about adding the commit of rollback to #286 ?

**Comment by duguorong009** [comment]
**NOTE**: Because of the [CI failure](https://github.com/privacy-scaling-explorations/halo2/actions/runs/8020043783/job/21909047859?pr=286#step:5:101), we keep the MSRV as `1.73.0`.
