### ISSUE TITLE
Update halo2curves dependency

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/halo2#326]
Update it to 0.6.1

**Comment by guorong009** [comment]
Do we really need this update?
According to this rust [doc](https://doc.rust-lang.org/cargo/reference/resolver.html), the dependency version is automatically resolved by resolver.

Anyhow, I've created the PR for best.

**Comment by ed255** [comment]
> Do we really need this update? According to this rust [doc](https://doc.rust-lang.org/cargo/reference/resolver.html), the dependency version is automatically resolved by resolver.
> 
> Anyhow, I've created the PR for best.

Oh you're right!  Previously we had 
```
halo2curves = { version = "0.6.1", default-features = false }
```
And the resolver would translate it to this constraint:
```
>=0.6.1, <1.0.0
```
Which includes `0.6.2`.
I didn't know about this before.  So I think we can avoid having this small unnecessary updates in the future :)
