### ISSUE TITLE
Remove unusable rows / poisoned cells

### ISSUE THREAD

**Issue by therealyingtong** [privacy-scaling-explorations/halo2#50]
Upstream randomises the last few rows in a circuit for the purpose of zero-knowledge. Since the zkEVM doesn't need zero-knowledge, we can remove the concept of unusable rows / poisoned cells.

It would be nice to have this as a feature flag.

**Comment by kilic** [comment]
Related with #73

**Comment by CPerezz** [comment]
Not necessary right now until we make clear waht to do with optional-ZK
