### ISSUE TITLE
proposal: allow add name to column

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/halo2#57]
to methods like `instance_column` , `advice_column` to help debugging

**Comment by CPerezz** [comment]
I think these kind of additions might be also benefitial in the upstream impl (in case they want them).

In any case, this is a quite big change so I think we should first check with @kilic who mainly takes care of rebasing upstream regularly to see how this would affect his work and if it would significantly increase conflicts at rebase/merge time with `upstream`.

cc @barryWhiteHat as we just talked about this topic.

**Comment by CPerezz** [comment]
@lispc I started some work on something similar to your proposal. See: https://github.com/zcash/halo2/pull/706

**Comment by jonathanpwang** [comment]
`Column<_>` implements Copy, so you probably don't want to add a string or even a `&str` to the struct itself. But you could have the `ConstraintSystem` keep a separate vector that maps column indices to column names, which the MockProver has access to. 

btw ideally do not use `dyn` closures for passing strings since that adds a slight runtime overhead.

**Comment by CPerezz** [comment]
> `Column<_>` implements Copy, so you probably don't want to add a string or even a `&str` to the struct itself. But you could have the `ConstraintSystem` keep a separate vector that maps column indices to column names, which the MockProver has access to. 
> 
> btw ideally do not use `dyn` closures for passing strings since that adds a slight runtime overhead.

If you check the impl, is not the Colum who holds a String but rather the Region struct. As the naming is done at synthesize time.

Also, from all the Assigment trait implementors only MockProver does hold the namigs. Which meanst ghat no overhead happens for the real Prover.
