### ISSUE TITLE
Add Keccak hash function in KZG for generating challenge

### ISSUE THREAD

**Issue by icemelon** [privacy-scaling-explorations/halo2#70]
We should use Keccak hash function in the last layer of the aggregation circuit to make the verifier contract easy and more efficient to implement in solidity. There should be a config to switch between Poseidon hash and Keccak hash.

**Comment by kilic** [comment]
There is an old PR #2 that adds keccak transcript. It should be rebased or ported. Also it can be delayed to the next upstream rebase.

**Comment by barryWhiteHat** [comment]
I think that @icemelon wants to have almost all Posidon and hten for the last transcript use Keccak. So we aggragate everything inside the zkps and the final keccak is done in smart contract.

**Comment by kilic** [comment]
@barryWhiteHat I think it amounts to same thing. we just need transcript implementations that implements `Transcript` for now blake2 is in the main poseidon and keccak are in PRs.

**Comment by CPerezz** [comment]
Closed via #2
