### ISSUE TITLE
[Action Required] Agreement to relicense v2022_05_09 of Halo2 Fork by the Privacy & Scaling Explorations Team

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/halo2#74]
Dear contributors,
Thank you for your past contributions to the Halo2 Fork by the Privacy & Scaling Explorations Team.

We post this issue to request your approval for the relicensing of the Halo2 Fork by the Privacy & Scaling Explorations Team. To express your consent, please respond to this issue with "I agree."

The Zcash Halo2 codebase (the upstream) was released under BOSL but relicensed to MIT + Apache2.0 recently. To change the downstream fork to the same license, we require approvals from all the past contributors that contributed to the extra downstream code.

Please see the license agreement in the [link](https://docs.google.com/document/d/1a0AkR91KxsRxQeRUTSJDZor-sLMAvb5kTRxWfRwFcVQ/edit#). 

The contributor list is acquired from the additional 66 commits to the upstream. 
https://github.com/zcash/halo2/compare/main...privacy-scaling-explorations:v2022_05_09

- [x] @kilic
- [x] @lispc
- [x] @AronisAt79
- [x] @ChihChengLiang
- [x] @CPerezz
- [x] @TrapdoorHeader
- [x] @Brechtpd
- [x] @spherel
- [x] @ntampakas
- [x] @han0110

**Comment by ChihChengLiang** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0.

**Comment by han0110** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0.

**Comment by ntampakas** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0.

**Comment by lispc** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0.

**Comment by Brechtpd** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0.

**Comment by AronisAt79** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0

**Comment by spherel** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0

**Comment by kilic** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0

**Comment by TrapdoorHeader** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling Explorations Team from BOSL to MIT + Apache2.0

**Comment by ChihChengLiang** [comment]
Thank you all, we now get all the approvals.

**Comment by CPerezz** [comment]
@ChihChengLiang should we make a PR to add the new licenses?

**Comment by ChihChengLiang** [comment]
@CPerezz yes sounds good. Resolved in #75

**Comment by spherel** [comment]
I agree to the relicensing of Halo2 Fork by the Privacy & Scaling
Explorations Team from BOSL to MIT + Apache2.0

AronisAt79 ***@***.***> 于 2022年6月1日周三 上午11:07写道：
