### ISSUE TITLE
Found an expression which would cause failure while verification when act as constraint

### ISSUE THREAD

**Issue by noel2004** [privacy-scaling-explorations/halo2#80]
I have found following simple express would cause wired issues when act as a constraint for a gate:

`Expression::Constant(Fp::zero()) - meta.query_advice(col, Rotation::cur())`

(`col` here indicate to a advice column)

I have purposed minimal code for reproducing this issue here: https://github.com/noel2004/halo2_issue/blob/master/tests/issue.rs

simply run `cargo test` to check the issue.

It cause no issue in MockProver but when we actually make a proof and try verify it, the verifier would complain.

And the issue could be elminted simple by swaping the two items, like:

`meta.query_advice(col, Rotation::cur()) - Expression::Constant(Fp::zero())`

Also, the upstream repo (zcash/halo2) with their pasta curve do not show this issue. (`issue_ref.rs` run the same code with zcash/halo2 and it can pass.)

**Comment by CPerezz** [comment]
Hey @noel2004 thanks for reporting this! :+1: 

At first look, it's weird that this happens as the expression construction should lead to the same exact thing. Might it be due to the caching that we do in the evaluations of the expressions to speed up halo2? It's one of the few things I can imagine at least for now.

cc: @brechtpd @han0110

**Comment by han0110** [comment]
Could be a typo here in `evaluation.rs#L407`, testing now

https://github.com/privacy-scaling-explorations/halo2/blob/1fc67702da729b41bfeebc9764c4c6effbd1f9ad/halo2_proofs/src/plonk/evaluation.rs#L400-L413

**Comment by han0110** [comment]
Yes, after updating evaluation.rs#407, the test passes. I have opened PR #81 to fix this.
