### ISSUE TITLE
backlog: speedup vk pk gen with multi thread

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/halo2#83]
eg: https://github.com/privacy-scaling-explorations/halo2/blob/f586922d19c3c96ffcec4adbe1790132565ffba6/halo2_proofs/src/plonk/permutation/keygen.rs#L110 it loop from 0 to 1<<k with single thread.

**Comment by LuozhuZhang** [comment]
PR is here #87

**Comment by CPerezz** [comment]
@pinkiebell picked this up from their branch. We should make a PR with the improvements that you did. Could you? Otherwise we will do it!

**Comment by pinkiebell** [comment]
@CPerezz Will do 👍
